version: '3.8'

services:
  memory-react:
    container_name: memory-react-dev
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
